### ISSUE TITLE
Keep getting undefined when trying to use this repo

### ISSUE THREAD

**Issue by sacredenty** [Ephenodrom/Flutter-Global-Config#33]
I tried loading from an asset and from a path to the file, neither work.
Seems to be failing because of a null check.
Log:
Restarted application in 243ms.
Error: Unexpected null value.
    at Object.throw_ [as throw] (http://localhost:60043/dart_sdk.js:5063:11)
    at Object.nullCheck (http://localhost:60043/dart_sdk.js:5390:30)
at load (http://localhost:60043/packages/flutter/src/services/restoration.dart.lib.js:6180:33)
    at load.next (<anonymous>)
    at runBody (http://localhost:60043/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:60043/dart_sdk.js:40242:7)
at asset_bundle.PlatformAssetBundle.new.load (http://localhost:60043/packages/flutter/src/services/restoration.dart.lib.js:6178:20)
at asset_bundle.PlatformAssetBundle.new.loadString (http://localhost:60043/packages/flutter/src/services/restoration.dart.lib.js:6039:32)
    at loadString.next (<anonymous>)
    at runBody (http://localhost:60043/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:60043/dart_sdk.js:40242:7)
at asset_bundle.PlatformAssetBundle.new.loadString (http://localhost:60043/packages/flutter/src/services/restoration.dart.lib.js:6038:20)
at http://localhost:60043/packages/flutter/src/services/restoration.dart.lib.js:6127:83
    at IdentityMap.new.putIfAbsent (http://localhost:60043/dart_sdk.js:27706:21)
at asset_bundle.PlatformAssetBundle.new.loadString (http://localhost:60043/packages/flutter/src/services/restoration.dart.lib.js:6127:57)
at global_configuration.GlobalConfiguration._internal.loadFromAsset (http://localhost:60043/packages/global_configuration/global_configuration.dart.lib.js:71:54)
    at loadFromAsset.next (<anonymous>)
    at runBody (http://localhost:60043/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:60043/dart_sdk.js:40242:7)
at global_configuration.GlobalConfiguration._internal.loadFromAsset (http://localhost:60043/packages/global_configuration/global_configuration.dart.lib.js:67:20)
at main$ (http://localhost:60043/packages/flutter_application_1/main.dart.lib.js:886:60)
    at main$.next (<anonymous>)
    at runBody (http://localhost:60043/dart_sdk.js:40211:34)
    at Object._async [as async] (http://localhost:60043/dart_sdk.js:40242:7)
at main$ (http://localhost:60043/packages/flutter_application_1/main.dart.lib.js:885:18)
at main (http://localhost:60043/web_entrypoint.dart.lib.js:36:29)
    at main.next (<anonymous>)
    at http://localhost:60043/dart_sdk.js:40192:33
    at _RootZone.runUnary (http://localhost:60043/dart_sdk.js:40062:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:60043/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:60043/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:60043/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:60043/dart_sdk.js:35437:23)
    at http://localhost:60043/dart_sdk.js:34617:46
    at _RootZone.runUnary (http://localhost:60043/dart_sdk.js:40062:59)
    at _FutureListener.then.handleValue (http://localhost:60043/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:60043/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:60043/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:60043/dart_sdk.js:35437:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:60043/dart_sdk.js:35458:35)
    at Object._microtaskLoop (http://localhost:60043/dart_sdk.js:40330:13)
    at _startMicrotaskLoop (http://localhost:60043/dart_sdk.js:40336:13)
    at http://localhost:60043/dart_sdk.js:35811:9

**Comment by sacredenty** [comment]
Using: global_configuration: ^2.0.0-nullsafety.1
